server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-bbml6pve.jp.auth0.com/
org:
  springframework:
    web:
      filter:
        CommonsRequestLoggingFilter: DEBUG
logging:
  level:
    org:
      springframework:
        security: DEBUG
#security:
#  oauth2:
#    resource:
#      jwk:
#        key-set-uri: http://localhost:8081/sso-auth-server/.well-known/jwks.json